### Updating a train
PATCH  http://localhost:5173/location/6459d1f8fba33f78264871ca
Content-Type: application/json

{
  "trainNumber": 724,
  "location": {
    "type": "Point",
    "coordinates": [89.4194, 49.7749]
  }
}

### Save a location
POST  http://localhost:3000/location
Content-Type: application/json

{
  "userID" : "1234567890",
  "trainNumber": 714,
  "location": {
    "type": "Point",
    "coordinates": [ 44.42622296431601,22.736238906491643]
  }
}

### Get estimated location for a train
GET http://localhost:3000/location/estimated/769
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQxNDA1NjEsImV4cCI6MTY4NDE0NDE2MSwiYXVkIjoiNjQ2MGMyYWM5MWU0YmIyNDkyNjMxNjJmIiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.T1qM8OsV1_n4y4LKWaldczI_QWLH9b2sE2BEa3_-arw

### Get all locations for a train
GET http://localhost:3000/location/769

### Get all locations
GET http://localhost:5173/location

### Get a location by id
GET http://localhost:5173/location/6459ccfa310db4ee4550cd3d

### Delete a location by id
DELETE http://localhost:5173/location/645a84f0e6bd270f0fd59ea9


### 404 Error
GET http://localhost:3000

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email" : "smtareqaziz7@gmail.com",
  "password" : "12345678",
  "isVerified" : false
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "smtareqaziz007@gmail.com",
  "password" : "12345678"
}

### authorized access
GET http://localhost:5173
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODM0NzE1NjMsImV4cCI6MTY4MzQ3OTE2NiwiYXVkIjoiNjQ1N2I3NWE1YmJjNjY3M2ZlOTM5NjM2IiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.CY3n0KgALStdxW2Y3XeQzzsSP63fyim192og-ycsqlQ

###Refresh token Route
POST http://localhost:5173/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODM0NDMxMzUsImV4cCI6MTcxNTAwMDczNSwiYXVkIjoiNjQ1NzRkYmY4NDkzZjFlYzk4MjJlMTAyIiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.7e-JM8hnkmUziGTPLoJOXySZ6HPyd8Y_6bM_F_gGaUo"
}

###Logout Route
DELETE http://localhost:5173/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODM0NzAyODYsImV4cCI6MTcxNTAyNzg4NiwiYXVkIjoiNjQ1N2I3NWE1YmJjNjY3M2ZlOTM5NjM2IiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.OoxiU_i6rJFzOJqkSeb6rvkhRwGHlz5etJJEo5r5rmU"
}

### Save a train
POST http://localhost:3000/train
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQxMjg3OTksImV4cCI6MTY4NDEzMjM5OSwiYXVkIjoiNjQ2MGMyYWM5MWU0YmIyNDkyNjMxNjJmIiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.qBPoGmx-hCsD0dbhvBdMVZ-0uuBqco7mLmTI-ZFRqN4

{
  "name" : "Ekota",
  "trainNumber" : 705,

  "to" : "B Sirajul Islam",
  "from" : "Dhaka",

  "departure" : "10:10 AM",
  "arrival" : "9:00 PM",
  "offDay" : "Wednesday",

  "isRunning" : false
}

### Get all trains
GET http://localhost:3000/train
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODQxMjg3OTksImV4cCI6MTY4NDEzMjM5OSwiYXVkIjoiNjQ2MGMyYWM5MWU0YmIyNDkyNjMxNjJmIiwiaXNzIjoicmFpbHNvbmRoYW4uY29tIn0.qBPoGmx-hCsD0dbhvBdMVZ-0uuBqco7mLmTI-ZFRqN4


### Get a train by id
GET http://localhost:5173/train/6457e3398a769c67a1a708b1

### Update by id
PATCH http://localhost:3000/train/6460cc27fef8620d0eb17521
Content-Type: application/json

{
  
  "departure" : "2:45 PM",
  "arrival" : "8:35 PM"

}

### Delete a train
DELETE http://localhost:5173/train/6459c5b9128b5f1cd3cac1ff